version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1juw7wdvbooqo"
s3_prefix = "api"
region = "us-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
